version: '2.4'
services:
  anchor-platform-server:
    image: anchor-platform
    command: "--sep-server"
    environment:
      - STELLAR_ANCHOR_CONFIG=file:/config/anchor-platform-config.yaml
      - SECRET_SEP10_SIGNING_SEED=${SECRET_SEP10_SIGNING_SEED?err}
      - SECRET_SEP10_JWT_SECRET=secret
      - SECRET_PLATFORM_API_AUTH_SECRET=myAnchorToPlatformSecret
      - SECRET_CALLBACK_API_AUTH_SECRET=myPlatformToAnchorSecret
      - SECRET_DATA_USERNAME=postgres
      - SECRET_DATA_PASSWORD=password
      - LOG_APPENDER=console_appender
    volumes:
      # add mounts for the new config directory
      - ./anchor-platform-default-configs:/config_defaults
    tmpfs:
      - /config
    depends_on:
      - db
      - kafka
    extra_hosts:
      - "host.docker.internal:host-gateway"

  stellar-observer:
    image: anchor-platform
    extends:
      file: ../docker-compose/common-services/common-services.yaml
      service: observer_a
    environment:
      - SECRET_SEP10_SIGNING_SEED=${SECRET_SEP10_SIGNING_SEED?err}
      - SECRET_SEP10_JWT_SECRET=secret
      - SECRET_PLATFORM_API_AUTH_SECRET=myAnchorToPlatformSecret
      - SECRET_CALLBACK_API_AUTH_SECRET=myPlatformToAnchorSecret
      - SECRET_DATA_USERNAME=postgres
      - SECRET_DATA_PASSWORD=password
      - LOG_APPENDER=console_appender

  anchor-reference-server:
    extends:
      file: ../docker-compose/common-services/common-services.yaml
      service: reference_server_a

  kafka:
    extends:
      file: ../docker-compose/common-services/common-services.yaml
      service: kafka_a

  zookeeper:
    extends:
      file: ../docker-compose/common-services/common-services.yaml
      service: zookeeper_a

  db:
    extends:
      file: ../docker-compose/common-services/common-services.yaml
      service: db_a

  end-to-end-tests:
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - anchor-platform-server
      - anchor-reference-server
    environment:
      - E2E_SECRET=${E2E_SECRET?err}
    extra_hosts:
      - "host.docker.internal:host-gateway"
