name: End-2-End Integration Tests

on:
  workflow_dispatch:
  workflow_call: # Allows this workflow to be called from another workflow
  push:
    branches:
      - main
#      - develop
      - 'release/**'
      - 'releases/**'
#      - 'hotfix/**'

jobs:
  integration_tests:
    runs-on: ubuntu-20.04
    env:
      E2E_SECRET: ${{ secrets.E2E_SECRET }}
      OMNIBUS_ALLOWLIST_KEYS: ${{ secrets.OMNIBUS_ALLOWLIST_KEYS }}
      SECRET_SEP10_SIGNING_SEED: ${{ secrets.SECRET_SEP10_SIGNING_SEED }}

    steps:
      - uses: actions/checkout@v3

      - name: Build images for integration tests
        run: make build-docker-compose-tests

      - name: Run integration tests (Default Config)
        run: make run-integration-test-default-config

      - name: Run integration tests (Unique Address)
        run: make run-integration-test-unique-address

      - name: Run integration tests (Allowlist)
        run: make run-integration-test-allowlist

      - name: Run integration tests (SEP 24 Withdraw)
        run: make run-integration-test-sep24-withdraw
